<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-left" href="timetable.jsp"><img src="/images/logo_home.png" style="width: 50%; height: 50%" ></a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li id="li_timetable" class="nav-item"><a class="nav-link" href="timetable.jsp">Horários</a></li>
				<li id="li_stations" class="nav-item"><a class="nav-link" href="stations.jsp">Estações</a></li>
				<li id="li_paths" class="nav-item"><a class="nav-link" href="paths.jsp">Rotas</a></li>
				<li id="li_holidays" class="nav-item"><a class="nav-link" href="holidays.jsp">Feriados</a></li>
				<li id="li_users" class="nav-item"><a class="nav-link" href="users.jsp">Usuários</a></li>
			</ul>
			<button class="btn btn-info float-right btn-sm"  onclick="location.href='login.jsp';">Sair</button>
		</div>
	</nav>
</header>