<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-left" href="index.jsp"><img src="/images/logo_home.png" style="width: 50%; height: 50%" ></a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item"><a class="nav-link" href="index.jsp">Horários</a></li>
				<li class="nav-item"><a class="nav-link" href="stations.jsp">Estações</a></li>
				<li class="nav-item"><a class="nav-link" href="paths.jsp">Rotas</a></li>
			</ul>
		</div>
	</nav>
</header>